### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by CmdrRoot** [thisistimothychen/umd-google-cal-schedule-importer#10]
When attempting to sign in an error is displayed. 

Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

**Comment by thisistimothychen** [comment]
Thanks for the note! I just pushed up a workaround to export the course schedule to an .ics file so that users can upload that to Google Calendar. There seems to be a new review process, so the patch will take a few business days to update. I'll keep this thread updated!

**Comment by thisistimothychen** [comment]
(Original context on this bug here: https://www.reddit.com/r/UMD/comments/esil73/get_your_class_schedule_in_google_calendar/ffe9blo/)

**Comment by thisistimothychen** [comment]
The extension's updated now so you should be able to export to .ics now! Let me know if anything isn't working as you would expect :) Closing this out as fixed!
